version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ../html:/var/www/html
      - ../internal:/var/www/internal
    depends_on:
      - db
    networks:
      - palestra-network

  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: palestra_db
    ports:
      - "3306:3306"
    volumes:
      - ../Database/db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - palestra-network

volumes:
  postgres_data:

networks:
  palestra-network:
    driver: bridge
